services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
  
  server: 
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URI=${DATABASE_URI:-postgres://postgres:postgres@db:5432/postgres}
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  db-data:
