services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limit:
          cpus: '0.5'
          memory: 512M
  
  server: 
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URI=${DATABASE_URI:-postgres://postgres:postgres@db:5432/postgres}
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  db-data:
